services:
  api:
    build:
      context: .
      # target: production  # Remove this line if not using multi-stage builds
    image: ips:001
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=database
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_RANDOM_ROOT_PASSWORD
    depends_on:
      - database
    restart: always

  database:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
